-- Run this once in Supabase SQL Editor.
-- The app uses SUPABASE_SERVICE_KEY server-side, so no public table policies are needed.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  gstin text not null unique,
  state text not null default 'Gujarat',
  state_code text not null default '24',
  hsn text not null default '998821',
  descriptions jsonb not null default '[]'::jsonb,
  description_rates jsonb not null default '{}'::jsonb,
  default_rate numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_no text not null unique,
  invoice_date date not null,
  buyer_name text not null,
  gstin text not null,
  hsn text not null,
  sub_desc text not null,
  qty numeric(12,2) not null,
  rate numeric(12,2) not null,
  taxable numeric(12,2) not null,
  cgst numeric(12,2) not null,
  sgst numeric(12,2) not null,
  round_off numeric(12,2) not null,
  total numeric(12,2) not null,
  pdf_base64 text not null,
  created_at timestamptz not null default now()
);
